Server:
  RunMode: debug
  HttpPort: 8888
  Readtimeout: 60
  WriteTimeout: 60
App:
  DefaultContextTimeout: 60
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/path
  UploadServerUrl: http://127.0.0.1:8888/static
  UploadImageMaxSize: 5 # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png  
Database:
  DBType: mysql
  Password: ****
  Username: root
  Host: 127.0.0.1:3306
  DBName: blog_service
  Tableprefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: ****
  Issuer: ****
  Expire: 7200
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: 871947276@qq.com
  Password: ****
  IsSSL: true
  From: 871947276@qq.com
  To:
